FROM alpine:latest

RUN apk add --no-cache curl

ENV VERSION 0.55.0
RUN mkdir -p /usr/local/src \
    && cd /usr/local/src \
    && curl -L https://github.com/gohugoio/hugo/releases/download/v${VERSION}/hugo_${VERSION}_linux-64bit.tar.gz | tar -xz \
    && mv hugo /usr/local/bin/hugo

RUN cd .. \
    mkdir /src

WORKDIR /src

ENTRYPOINT [ "hugo" ]